### PR TITLE
fix: failing readiness probe when replica > 1

### LINKED ISSUE #1617: Failing readiness probe on 2.8.0 when replicas>1
**What happened**:
After upgrading from `2.7.1` to `2.8.0` readiness probe is failing on 2 of 3 replicas of `hami-scheduler/vgpu-scheduler-extender`. Looks that only currently elected master is green, rest is yellow. It bothers ArgoCD and it's confusing for people maintaining environment. Otherwise HAMI functions properly.

**What you expected to happen**:
All replicas should be green all the time.

**How to reproduce it (as minimally and precisely as possible)**:
Set such values for HELM chart:
```
scheduler:
  replicas: 3
  leaderElect: true
```

**Environment**:
- HAMi version: 2.8.0

### PR DESCRIPTION
**Pull request by Shouren**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
As described in #1617, the PR #1553 brings the readinessProbe check for vgpu-scheduler-extender container in hami-scheduler Pod, however it the current implementation don't work well with the rolling update strategy of deployment.

So in this PR, A new label is introduced to make sure that only the leader is selected by the service

**Which issue(s) this PR fixes**:
Fixes #1617

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

**AI Assistant disclosure**:
I used kimi-cli to generate the testing code

### CODE REVIEW

File: pkg/scheduler/scheduler.go [hunk 1]
```diff
@@ -353,11 +354,45 @@ func (s *Scheduler) register(labelSelector labels.Selector, printedLog map[strin
...
+			if err != nil {
+				klog.ErrorS(err, "Failed to patch leader label to pod", "namespace", os.Getenv("POD_NAMESPACE"), "pod", os.Getenv("POD_NAME"))
+			} else {
+				klog.V(4).InfoS("Successfully patched leader label to hami scheduler pod", "namespace", os.Getenv("POD_NAMESPACE"), "pod", os.Getenv("POD_NAME"))
+			}
+		}
+	} else {
+		// Current pod is not leader, add or change the role label to follower
+		if pod.Labels != nil && pod.Labels[util.HAMiRoleLabel] != util.HAMiRoleLabelValueFollower {
+			err := util.PatchPodLabels(
```
Comment (FouoF) [inline pkg/scheduler/scheduler.go]: The follower update their roles themself may not reliable. If the leader crash, the role label will not be updated and two leader will exist together (Though the crashed one will removed from the endpoint slice). Let the leader to update previous leader to follower may be more reliable.

Comment (Shouren) [reply pkg/scheduler/scheduler.go]: @FouoF Done.

**Comment by krzysztof-magosa** [comment]
@Shouren hi, any idea when this will be released? thanks

**Comment by Shouren** [comment]
> @Shouren hi, any idea when this will be released? thanks

@krzysztof-magosa It supposed to be released next month(maybe second week) in v2.9.0
