### PR TITLE
fix: Before executing MIG partitioning, suppress NVML usage in o…

### LINKED ISSUE #1088: Mig apply error show nvidia-mig-parted failed with code
**What happened**:
Mig split fails and causes device plugin to exit and restart

**What you expected to happen**:
Mig part succeed

**How to reproduce it (as minimally and precisely as possible)**:
Normal 1 node with 1 gpu, test  dynamic-mig

**Anything else we need to know?**:
1.too many open nvidia device
```
[root@node-37 ~]# lsof /dev/nvidia0
COMMAND     PID USER   FD   TYPE DEVICE SIZE/OFF      NODE NAME
nvidia-de 17448 root    8u   CHR  195,0      0t0 128342862 /dev/nvidia0
nvidia-de 17448 root   13u   CHR  195,0      0t0 128342862 /dev/nvidia0
nvidia-de 17448 root   15u   CHR  195,0      0t0 128342862 /dev/nvidia0
nvidia-de 17448 root   21u   CHR  195,0      0t0 128342862 /dev/nvidia0
vGPUmonit 53165 root    9u   CHR  195,0      0t0 128342862 /dev/nvidia0
```
2. I closed vGPUmonit container
3.I update code to close device occupy
```
diff --git a/pkg/device-plugin/nvidiadevice/nvinternal/plugin/register.go b/pkg/device-plugin/nvidiadevice/nvinternal/plugin/register.go
index 7e2edba..9b1c42a 100644
--- a/pkg/device-plugin/nvidiadevice/nvinternal/plugin/register.go
+++ b/pkg/device-plugin/nvidiadevice/nvinternal/plugin/register.go
@@ -111,6 +111,7 @@ func parseNvidiaNumaInfo(idx int, nvidiaTopoStr string) (int, error) {
 
 func (plugin *NvidiaDevicePlugin) getAPIDevices() *[]*util.DeviceInfo {
 	devs := plugin.Devices()
+	defer nvml.Shutdown()
 	klog.V(5).InfoS("getAPIDevices", "devices", devs)
 	if nvret := nvml.Init(); nvret != nvml.SUCCESS {
 		klog.Errorln("nvml Init err: ", nvret)
diff --git a/pkg/device-plugin/nvidiadevice/nvinternal/plugin/server.go b/pkg/device-plugin/nvidiadevice/nvinternal/plugin/server.go
index 3bfecc3..23f2bee 100644
--- a/pkg/device-plugin/nvidiadevice/nvinternal/plugin/server.go
+++ b/pkg/device-plugin/nvidiadevice/nvinternal/plugin/server.go
@@ -244,12 +244,12 @@ func (plugin *NvidiaDevicePlugin) Start() error {
 		plugin.migCurrent.MigConfigs["current"] = HamiInitMigConfig
 		klog.Infoln("Mig export", plugin.migCurrent)
 	}
-	go func() {
-		err := plugin.rm.CheckHealth(plugin.stop, plugin.health)
-		if err != nil {
-			klog.Infof("Failed to start health check: %v; continuing with health checks disabled", err)
-		}
-	}()
+	// go func() {
+	// 	err := plugin.rm.CheckHealth(plugin.stop, plugin.health)
+	// 	if err != nil {
+	// 		klog.Infof("Failed to start health check: %v; continuing with health checks disabled", err)
+	// 	}
+	// }()
 
 	go func() {
 		plugin.WatchAndRegister()
diff --git a/pkg/device-plugin/nvidiadevice/nvinternal/plugin/util.go b/pkg/device-plugin/nvidiadevice/nvinternal/plugin/util.go
index bf8521c..645c51e 100644
--- a/pkg/device-plugin/nvidiadevice/nvinternal/plugin/util.go
+++ b/pkg/device-plugin/nvidiadevice/nvinternal/plugin/util.go
@@ -94,6 +94,7 @@ func EraseNextDeviceTypeFromAnnotation(dtype string, p corev1.Pod) error {
 }
 
 func GetIndexAndTypeFromUUID(uuid string) (string, int) {
+	defer nvml.Shutdown()
 	if nvret := nvml.Init(); nvret != nvml.SUCCESS {
 		klog.Errorln("nvml Init err: ", nvret)
 		panic(0)
@@ -150,6 +151,7 @@ func GetMigUUIDFromSmiOutput(output string, uuid string, idx int) string {
 }
 
 func GetMigUUIDFromIndex(uuid string, idx int) string {
+	defer nvml.Shutdown()
 	if nvret := nvml.Init(); nvret != nvml.SUCCESS {
 		klog.Errorln("nvml Init err: ", nvret)
 		panic(0)
@@ -184,6 +186,7 @@ func GetMigUUIDFromIndex(uuid string, idx int) string {
 }
 
 func GetDeviceNums() (int, error) {
+	defer nvml.Shutdown()
 	if nvret := nvml.Init(); nvret != nvml.SUCCESS {
 		klog.Errorln("nvml Init err: ", nvret)
 		return 0, fmt.Errorf("nvml Init err: %s", nvml.ErrorString(nvret))
@@ -209,7 +212,7 @@ func (nv *NvidiaDevicePlugin) ApplyMigTemplate() {
 	cmd.Stderr = &stderr
 	err = cmd.Run()
 	if err != nil {
-		klog.Fatalf("nvidia-mig-parted failed with %s\n", err)
+		klog.Fatalf("nvidia-mig-parted failed with %s,reason:%s\n", err, stderr.String())
 	}
 	outStr := stdout.String()
 	klog.Infoln("Mig apply", outStr)

```
at last,it's ok
```
[root@node-37 ~]# kubectl  get pod -n hami  -o wide
NAME                              READY   STATUS    RESTARTS   AGE     IP            NODE      NOMINATED NODE   READINESS GATES
gpu-pod                           1/1     Running   0          12m     10.232.6.29   node-37   <none>           <none>
hami-device-plugin-89585          1/1     Running   0          13m     10.53.1.10    node-37   <none>           <none>
hami-scheduler-744879cfc4-6f9mq   2/2     Running   0          4d21h   10.232.6.22   node-37   <none>           <none>
[root@node-37 ~]# lsof /dev/nvidia0
[root@node-37 ~]# nvidia-smi -L
GPU 0: NVIDIA A100-PCIE-40GB (UUID: GPU-102c6326-b245-a618-ebc5-c8d3c6f9fa34)
  MIG 1g.5gb      Device  0: (UUID: MIG-9b4117dd-8cd2-569b-b714-7abfda17507f)
  MIG 1g.5gb      Device  1: (UUID: MIG-723c973d-f886-5707-b5b6-e2258d7d9c0b)
  MIG 1g.5gb      Device  2: (UUID: MIG-a4dbed86-8574-54cf-877f-558cf0b57104)
  MIG 1g.5gb      Device  3: (UUID: MIG-9659f28f-0b9b-5dbc-a71f-25262f350637)
  MIG 1g.5gb      Device  4: (UUID: MIG-5ff57cdc-44ce-533c-8cea-1fc391308243)
  MIG 1g.5gb      Device  5: (UUID: MIG-3fc9a8b2-c598-5454-903f-ddaa5bdaa75e)
  MIG 1g.5gb      Device  6: (UUID: MIG-e3745d9a-aab5-590e-9d6e-c72a3514cbcf)
```
So we should pay attention to maintaining the call to the nvml library in the code and closing it in time to maintain the stability of the mig function.
Especially when the call is not closed in the goroutine and is called at time intervals, it is easy to conflict with the mig parted operation.

**Environment**: 
- HAMi version: latest
- nvidia driver or other AI device driver version:
- Docker version from `docker version`
- Docker command, image and tag used
- Kernel version from `uname -a`
- Others:

### PR DESCRIPTION
**Pull request by Goend**
…ther goroutines. (#1088)

**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
Before executing MIG partitioning, suppress NVML usage in other goroutines.

**Which issue(s) this PR fixes**:
Fixes #1088

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

### CODE REVIEW

**Comment by Goend** [comment]
@archlitchi  need review

**Comment by archlitchi** [comment]
have you tested on your local environment?

**Comment by Goend** [comment]
> have you tested on your local environment?

yes

**Comment by archlitchi** [comment]
great!, i'll try it on my local environment

File: pkg/device-plugin/nvidiadevice/nvinternal/plugin/lock.go [hunk 1]
```diff
@@ -0,0 +1,114 @@
...
+}
+
+func watchLockFile(file string) (chan bool, error) {
+	sigChan := make(chan bool, 1)
+	watcher, err := fsnotify.NewWatcher()
+	if err != nil {
+		return nil, err
+	}
+	dir := filepath.Dir(file)
+	if err := watcher.Add(dir); err != nil {
```
Comment (Shouren) [inline pkg/device-plugin/nvidiadevice/nvinternal/plugin/lock.go:97]: Does this means we watch all the files in `/tmp` directory? I do not think it is a good idea to do so.

Comment (Shouren) [reply pkg/device-plugin/nvidiadevice/nvinternal/plugin/lock.go:97]: I check the `DaemonSet` config of `hami-device-plugin`, the `/tmp` is mounted using `hostPath`.

Comment (Goend) [reply pkg/device-plugin/nvidiadevice/nvinternal/plugin/lock.go:97]: Regarding the reasons for monitoring the /tmp directory here:

    1.The fsnotify library itself recommends monitoring the parent directory rather than individual files.And when file is not existed,the  fsnotify library will give one error.

    2.The /tmp directory is the only host directory shared between the device plugin container and the vgpu monitor. Otherwise, we would need to modify the Helm chart. To minimize changes, we opted to monitor this directory directly.
    3.The watcher.Events will return only change event,the /tmp directory returns only changed events even if it contains a large number of files – the actual output isn't that extensive

Comment (Goend) [reply pkg/device-plugin/nvidiadevice/nvinternal/plugin/lock.go:97]: Therefore, based on the reasons above, I don't think we need to make changes here. Just like the mig exported files are located in this directory, we've actually been using this directory for a while now. What do you think? @Shouren

Comment (Shouren) [reply pkg/device-plugin/nvidiadevice/nvinternal/plugin/lock.go:97]: @Goend 
Agreed with 1 & 2. 
As for 3, i am considering how to reduce the watcher.Events in `/tmp`. As mentioned in fsnotify's [doc](https://pkg.go.dev/github.com/fsnotify/fsnotify#Watcher):
>``` Go
> //   fsnotify.Write     A file or named pipe was written to. A Truncate will
> //                      also trigger a Write. A single "write action"
> //                      initiated by the user may show up as one or multiple
> //                      writes, depending on when the system syncs things to
> //                      disk. For example when compiling a large Go program
> //                      you may get hundreds of Write events, and you may
> //                      want to wait until you've stopped receiving them
> //                      (see the dedup example in cmd/fsnotify).
>```
Because `/tmp` is mounted from the host's `/tmp`, and we cannot control the behavior of users on the host, the chance of an `ErrEventOverflow` error increases.
So my suggestions would be **creating a sub directory in `/tmp` and watch this directory** or **Show a warn that the value of `fs.inotify.max_queued_events` in `sysctl.conf` should be increased**.

Comment (Goend) [reply pkg/device-plugin/nvidiadevice/nvinternal/plugin/lock.go:97]: Sub directory should be a more suitable option, so I will change it.

Comment (Goend) [reply pkg/device-plugin/nvidiadevice/nvinternal/plugin/lock.go:97]: done

Comment (Goend) [reply pkg/device-plugin/nvidiadevice/nvinternal/plugin/lock.go:97]: The CreateMigApplyLockDir function has been used to ensure that the /tmp/hami subdirectory is created during the startup of the device plugin and vGPU monitor.

**Comment by ouyangluwei163** [comment]
> @ouyangluwei163 If you have time, I hope you can help conduct an overall review to expedite moving this patch into the branch and help stabilize the main branch's MIG partitioning,thanks a lot.

Ok, this week is a bit busy, I will test it next week.

**Comment by Goend** [comment]
@ouyangluwei163  Since I will no longer have access to the test environment next week, it may be necessary to conduct a code review beforehand so that I can handle the related code changes.

**Comment by ouyangluwei163** [comment]
> @ouyangluwei163 Since I will no longer have access to the test environment next week, it may be necessary to conduct a code review beforehand so that I can handle the related code changes.

OK, I have started today.
