### PR TITLE
fix: resolve cardinality explosion in Device_memory_desc_of_container

### LINKED ISSUE #1623: Metric Device_memory_desc_of_container causes time series explosion due to unbounded data label.
**What happened**:
The metric `Device_memory_desc_of_container` uses the actual memory value (in bytes) as a label named `data`, instead of using it as the metric value itself. This design causes severe time series cardinality explosion in Prometheus/VictoriaMetrics.
such as：
{__name__="Device_memory_desc_of_container", context="155189248", ctrname="xzy-test-1", data="2453799936", deviceuuid="GPU-e1abbb55-43f6-29a0-86d8-01afb4ec1ebe", endpoint="monitorport", instance="192.168.13.210:9394", job="hami-device-plugin-monitor", module="0", namespace="kube-system", offset="0", pod="hami-device-plugin-wlm66", podname="xzy-test-1-9df9d7db4-g86ks", podnamespace="ns-admin", prometheus="vm/vm-stack-victoria-metrics-k8s-stack", service="hami-device-plugin-monitor", vdeviceid="0", zone="vGPU"}

**What you expected to happen**:
The memory value should be the metric value, not a label.

**How to reproduce it (as minimally and precisely as possible)**:
Deploy HAMi device plugin with monitoring enabled.
Create a pod with GPU allocation.
Query Prometheus/VictoriaMetrics.

**Anything else we need to know?**:
Root cause: In the device plugin monitor code, the metric is defined with data as a label:

ctrDeviceMemorydesc = prometheus.NewDesc(
    "Device_memory_desc_of_container",
    "Container device memory description",
    []string{"podnamespace", "podname", "ctrname", "vdeviceid", 
             "deviceuuid", "context", "module", "data", "offset"},  // ← "data" should not be here
    nil,
)

**Environment**:
- HAMi version:  hami-2.8.0

### PR DESCRIPTION
**Pull request by maishivamhoo123**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
This PR fixes a time series cardinality explosion in Prometheus. 
The metric `Device_memory_desc_of_container` was using dynamic memory values as labels. 
I have removed these labels and moved the memory data to the actual metric value.

**Which issue(s) this PR fixes**:
Fixes #1623

**Special notes for your reviewer**:
I removed the unused variables `memoryContextSize`, `memoryModuleSize`, `memoryBufferSize`, and `memoryOffset` to satisfy the Go compiler after removing them from the labels.

**Does this PR introduce a user-facing change?**:
No

### CODE REVIEW

File: cmd/vGPUmonitor/metrics.go [hunk 1]
```diff
@@ -393,10 +393,6 @@ func (cc ClusterManagerCollector) collectContainerMetrics(ch chan<- prometheus.M
 		// Collect device metrics
 		memoryTotal := c.Info.DeviceMemoryTotal(i)
 		memoryLimit := c.Info.DeviceMemoryLimit(i)
-		memoryContextSize := c.Info.DeviceMemoryContextSize(i)
-		memoryModuleSize := c.Info.DeviceMemoryModuleSize(i)
-		memoryBufferSize := c.Info.DeviceMemoryBufferSize(i)
```
Comment (dongjiang1989) [inline cmd/vGPUmonitor/metrics.go:398]: Change context size, module size and buffer size with new metrics series? wdyt？

Comment (maishivamhoo123) [reply cmd/vGPUmonitor/metrics.go:398]: Yeah, that makes sense. These represent different memory dimensions, so we should expose them. Sorry I missed this earlier — I’ll make a PR to add them as a separate metrics series.

File: cmd/vGPUmonitor/metrics.go [hunk 2]
```diff
@@ -106,8 +106,8 @@ var (
 	)
 	ctrDeviceMemorydesc = prometheus.NewDesc(
 		"Device_memory_desc_of_container",
-		"Container device memory description",
-		[]string{"podnamespace", "podname", "ctrname", "vdeviceid", "deviceuuid", "context", "module", "data", "offset"}, nil,
+		"Container device memory description (Deprecated: use vGPU_device_memory_usage_in_bytes instead)",
+		[]string{"podnamespace", "podname", "ctrname", "vdeviceid", "deviceuuid"}, nil,
```
Comment (FouoF) [inline cmd/vGPUmonitor/metrics.go]:
```suggestion
		[]string{"podnamespace", "podname", "ctrname", "vdeviceid", "deviceuuid", "context", "module", "data", "offset"}, nil,
```
This should not actually deprecate until next version release.

File: cmd/vGPUmonitor/metrics.go [hunk 3]
```diff
@@ -106,8 +106,8 @@ var (
 	)
 	ctrDeviceMemorydesc = prometheus.NewDesc(
 		"Device_memory_desc_of_container",
-		"Container device memory description",
-		[]string{"podnamespace", "podname", "ctrname", "vdeviceid", "deviceuuid", "context", "module", "data", "offset"}, nil,
+		"Container device memory description (Deprecated: use vGPU_device_memory_usage_in_bytes instead)",
```
Comment (FouoF) [inline cmd/vGPUmonitor/metrics.go]:
```suggestion
		`Container device memory description (The label "context", "module", "data" and "offset" will be deprecated in v2.10.0, use vGPU_device_memory_context_size_bytes, vGPU_device_memory_module_size_bytes and vGPU_device_memory_buffer_size_bytes instead)`,
```

**Comment by maishivamhoo123** [comment]
@FouoF and @Shouren sir can you please review the changes?

File: cmd/vGPUmonitor/metrics.go [hunk 4]
```diff
@@ -396,40 +418,48 @@ func (cc ClusterManagerCollector) collectContainerMetrics(ch chan<- prometheus.M
...
 		}
 
 		if err := sendMetric(ch, ctrDeviceUtilizationdesc, prometheus.GaugeValue, float64(smUtil), labels...); err != nil {
-			klog.Errorf("Failed to send SM utilization metric for device %d in Pod %s/%s, Container %s: %v", i, pod.Namespace, pod.Name, ctr.Name, err)
+			klog.Errorf("Failed to send device utilization desc: %v", err)
+			return err
+		}
+
+		if err := sendMetric(ch, ctrDeviceMemoryContextDesc, prometheus.GaugeValue, float64(memoryContextSize), labels...); err != nil {
+			klog.Errorf("Failed to send context size metric: %v", err)
```
Comment (Shouren) [inline cmd/vGPUmonitor/metrics.go]: @maishivamhoo123 Please add 'Device Memory' to the error message for this one and the followings, it confused me when i see the error "Failed to send module size metric".
